export const TOGGLE_AD_TYPE_SUCCESS = "TOGGLE_AD_TYPE_SUCCESS";

export const SELECT_PRESENTATION_TIME = "SELECT_PRESENTATION_TIME";

export const GET_CATEGORY_PRICES_INFO_SUCCESS =
    "GET_CATEGORY_PRICES_INFO_SUCCESS";
export const GET_CATEGORY_PRICES_INFO_PENDING =
    "GET_CATEGORY_PRICES_INFO_PENDING";
export const GET_CATEGORY_PRICES_INFO_FAILED =
    "GET_CATEGORY_PRICES_INFO_FAILED";

export const SET_AD_TYPES_AND_PRESENTATION_TIME_SUCCESS =
    "SET_AD_TYPES_AND_PRESENTATION_TIME_SUCCESS";
export const SET_AD_TYPES_AND_PRESENTATION_TIME_PENDING =
    "SET_AD_TYPES_AND_PRESENTATION_TIME_PENDING";
export const SET_AD_TYPES_AND_PRESENTATION_TIME_FAILED =
    "SET_AD_TYPES_AND_PRESENTATION_TIME_FAILED";

export const CREATE_DRAFT_SUCCESS = "CREATE_DRAFT_SUCCESS";
export const CREATE_DRAFT_PENDING = "CREATE_DRAFT_PENDING";
export const CREATE_DRAFT_FAILED = "CREATE_DRAFT_FAILED";

export const GET_LISTING_ADS_DRAFT_PRODUCTS_SUCCESS =
    "GET_LISTING_ADS_DRAFT_PRODUCTS_SUCCESS";
export const GET_LISTING_ADS_DRAFT_PRODUCTS_PENDING =
    "GET_LISTING_ADS_DRAFT_PRODUCTS_PENDING";
export const GET_LISTING_ADS_DRAFT_PRODUCTS_FAILED =
    "GET_LISTING_ADS_DRAFT_PRODUCTS_FAILED";

export const CHANGE_AD_TYPE_PROPERTIES_SUCCESS =
    "CHANGE_AD_TYPE_PROPERTIES_SUCCESS";

export const CHANGE_TOTAL_PRICE_BY_GIVEN_AMOUNT_SUCCESS =
    "CHANGE_TOTAL_PRICE_BY_GIVEN_AMOUNT_SUCCESS";

export const GET_DRAFT_SUCCESS = "GET_DRAFT_SUCCESS";
export const GET_DRAFT_PENDING = "GET_DRAFT_PENDING";
export const GET_DRAFT_FAILED = "GET_DRAFT_FAILED";

export const CHECK_FORCE_UPDATE_SUCCESS = "CHECK_FORCE_UPDATE_SUCCESS";
export const CHECK_FORCE_UPDATE_FAILED = "CHECK_FORCE_UPDATE_FAILED";
export const CHECK_FORCE_UPDATE_PENDING = "CHECK_FORCE_UPDATE_PENDING";
